/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "remote.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Subscribe, Subscribe, AUTO)


PB_BIND(Unsubscribe, Unsubscribe, AUTO)


PB_BIND(Publish, Publish, 2)


PB_BIND(UARTConnected, UARTConnected, AUTO)


PB_BIND(RemoteMsg, RemoteMsg, 2)



